---
# tasks file for common
- block:
    - name: set timezone to {{ timezn}}
      timezone:
        name: "{{ timezn }}"

    - name: change hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: update apt cache
      apt:
        update_cache: yes

    - name: create a swap file {{ swapfl }}
      shell: fallocate -l {{ swap_size }} {{ swapfl }}
      args:
        creates: "{{ swapfl }}"

    - name: set the correct permissions
      file:
        path: "{{ swapfl }}"
        owner: root
        group: root
        mode: '0600'

    - name: make the file a swap file
      shell: mkswap {{ swapfl }}
      when: ansible_facts.swapfree_mb == 0

    - name: enable the swap file
      shell: swapon {{ swapfl }}
      when: ansible_facts.swapfree_mb == 0

    - name: add swap file to fstab
      mount:
        name: none
        src: "{{ swapfl }}"
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present
  become: yes
